config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [ :new, :create, :index ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :address, presence: true
  validates :name, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"], allow_nil: false }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, inclusion: { in: 1..5, allow_nil: false }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController



 before_action :set_restaurant, only: [:show, :edit, :update, :destroy]


 def index
    @restaurants = Restaurant.all
  end

 def new
    @restaurant = Restaurant.new
  end

 def show
    @restaurant = Restaurant.find(params[:id])

 #  assigns the requested restaurant as @restaurant (FAILED - 1)

 end

 def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

 def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

   # no need for app/views/tasks/destroy.html.erb
    redirect_to restaurants_path
  end

 def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save

   # assigns a newly created but unsaved restaurant as @restaurant (FAILED - 2)
    #  re-renders the ‘new’ template (FAILED - 3)

   redirect_to restaurant_path(@restaurant)
  end

 def edit
    @restaurant = Restaurant.find(params[:id])
  end

 private

 def restaurant_params
      # *Strong params*: You need to *whitelist* what can be updated by the user
      # Never trust user data!

     params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

 def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController


before_action :set_review, only: [:new, :create]



 def index

    @reviews = Review.all
  end


def new

# we need @restaurant in our `simple_form_for`

#@restaurant = Restaurant.find(params[:restaurant_id])

@review = Review.new
end

def create

@review = Review.new(review_params)

# we need `restaurant_id` to asssociate review with corresponding restaurant

@review.restaurant = @restaurant
@review.save
redirect_to restaurant_path(@restaurant)
end

private

def review_params
  params.require(:review).permit(:content, :rating)
end

def set_review
  @restaurant = Restaurant.find(params[:restaurant_id])
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<h1>EDIT</h1>

app/views/restaurants/index.html.erb
<h1>INDEX</h1>



<%= link_to 'Adicionar restaurante:', new_restaurant_path, class: 'btn btn-default' %>

<br>
<br>
<br>

<% @restaurants.each do |restaurant| %>


  Nome: <%= restaurant.name %>

  <%= link_to 'Ver Detalhe', restaurant_path(restaurant), class: 'btn btn-default' %>
  <hr>
<%end%>

app/views/restaurants/new.html.erb
<h1>NEW</h1>


<div class='row'>
  <div class='col-md-6'>


  <%= form_for(@restaurant) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :category %>
    <%= f.select :category, ["chinese", "italian", "japanese", "french", "belgian"], {}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_area :address, class: 'form-control', rows: 10 %>
  </div>

  <%= f.submit 'Salvar', class: 'btn btn-primary btn-block' %>
<%end%>



  </div>
</div>

app/views/restaurants/show.html.erb
<h1>SHOW</h1>



<h3>Detalhe do Restaurante</h3>

<br>
  Nome: <%= @restaurant.name %>
<br>
  Categoria: <%= @restaurant.address %>
<br>
  Telefone: <%= @restaurant.phone_number %>
<br>
  Categoria: <%= @restaurant.category %>
<br>




<%= link_to 'Voltar', restaurants_path, class: 'btn btn-default' %>

<%= link_to 'Editar Restaurante', edit_restaurant_path(@restaurant), class: 'btn btn-info' %>

<%= link_to 'Fazer Review', new_restaurant_review_path(@restaurant), class: 'btn btn-default' %>

<%= link_to 'Ver Reviews', restaurant_reviews_path(@restaurant), class: 'btn btn-default' %>

app/views/reviews/index.html.erb
<h1> INDEX REVIEWS</h1>



<% @reviews.each do |review| %>


  Rating: <%= review.rating %>
  Comment: <%= review.content %>
  <hr>
<%end%>



<%= link_to 'Voltar', restaurants_path, class: 'btn btn-default' %>
<%= link_to 'Fazer Review', new_restaurant_review_path, class: 'btn btn-default' %>

app/views/reviews/new.html.erb
<h1>NEW REVIEW</h1>


<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :rating %>
  <%= f.input :content %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>